#!/bin/bash

set -eu -o pipefail
readonly SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
readonly LIB_DIR=${SCRIPT_DIR}
. "${LIB_DIR}/common"
. "${CONFIG_FILE}"

FORMAT=tar.bz2.gpg

src_dir="$1"
category="$2"
reminder="$3"

base_dir=`dirname "$src_dir"`
item_name=`basename "$src_dir"`

bz2_file_name=${item_name}.tar.bz2
tar -cjf "$bz2_file_name" -C "$base_dir" "$item_name"

gpg_file_name=${bz2_file_name}.gpg
gpg_with_password "${reminder}" -o "${gpg_file_name}" --symmetric "${bz2_file_name}"
rm "$bz2_file_name"

timestamp=`find_timestamp "$src_dir"`
description="$category/$item_name/$timestamp/$FORMAT/$reminder"
file_size=`ls -l "$gpg_file_name" | cut -d ' ' -f 5`

output=`aws glacier upload-archive --account-id $ACCOUNT --vault $VAULT --archive-description "$description" --body "$gpg_file_name"`
rm "$gpg_file_name"

archive_id=`echo "$output" | grep archiveId | cut -d '"' -f 4`
echo "$category	$item_name	$timestamp	$FORMAT	$file_size	$reminder	$archive_id"
