#!/bin/bash

set -eu -o pipefail

readonly SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
readonly LIB_DIR=${SCRIPT_DIR}
. "${LIB_DIR}/common"
. "${CONFIG_FILE}"


function cmd_up() {
  "${LIB_DIR}/agar-up" "$@" >> "${INDEX_FILE}"
}

function cmd_index() {
  "${LIB_DIR}/agar-index" "$@"
}

function show_usage() {
    echo "usage: $0 <command> <options>"
    echo
    echo "commands:"
    echo "  up <source-directory> <category> <password-reminder>"
    echo "  index <sub-command>"
}

if [ $# == 0 ]; then
  show_usage
  exit 1
fi

readonly command=$1
shift

case ${command} in
  index)
    cmd_index "$@"
    ;;
  up)
    cmd_up "$@"
    ;;
  *)
    show_usage
    exit 1
esac
