[package]
name = "agar"
version = "0.1.0"
authors = ["Maciek Makowski <public@mmakowski.com>"]
edition = "2018"

[dependencies]
clap = "2.32.0"
rusoto_core = "0.37.0"
rusoto_glacier = "0.37.0"

[dev-dependencies]
tempdir = "0.3.7"
